title usage and location

rectangle redis_package{
    class RedisKV{
        mapValue
        prefix
        redis
        type
        ---
        setValue()
        getValue()
        deleteValue()
    }
    class SessionStore{
        sharedGlobalStore
        randomKeyGenerator
        store
        ---
        setValue() 
        deleteValue()
    }
    class StoreContext{
        authenticationField
        cookiesOptions
        ---
        initSession()
        getSession()
        getSessionId()
        updateSession()
        destroySession()
        isUserAuthenticated()
    }

    class AuthAttempt{
        isKeyExpired()
        clearExpired()
        fail()
        getAttempt()
        success()
    }
}

rectangle openId{

}

rectangle receiptBank{

}

rectangle service_auth{

}

rectangle service_quickBooks{

}
SessionStore <-- StoreContext

RedisKV <- SessionStore
RedisKV <- AuthAttempt

StoreContext <-- receiptBank

AuthAttempt <--- service_auth

SessionStore <-- service_quickBooks

StoreContext <-- service_quickBooks

RedisKV <--- openId